// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageNotifyExpeditionInfo.proto

#ifndef PROTOBUF_MessageNotifyExpeditionInfo_2eproto__INCLUDED
#define PROTOBUF_MessageNotifyExpeditionInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageNotifyExpeditionInfo_2eproto();
void protobuf_AssignDesc_MessageNotifyExpeditionInfo_2eproto();
void protobuf_ShutdownFile_MessageNotifyExpeditionInfo_2eproto();

class NotifyExpeditionInfo;

// ===================================================================

class NotifyExpeditionInfo : public ::google::protobuf::Message {
 public:
  NotifyExpeditionInfo();
  virtual ~NotifyExpeditionInfo();

  NotifyExpeditionInfo(const NotifyExpeditionInfo& from);

  inline NotifyExpeditionInfo& operator=(const NotifyExpeditionInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NotifyExpeditionInfo& default_instance();

  void Swap(NotifyExpeditionInfo* other);

  // implements Message ----------------------------------------------

  NotifyExpeditionInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NotifyExpeditionInfo& from);
  void MergeFrom(const NotifyExpeditionInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mode1curstage = 1;
  inline bool has_mode1curstage() const;
  inline void clear_mode1curstage();
  static const int kMode1CurstageFieldNumber = 1;
  inline ::google::protobuf::int32 mode1curstage() const;
  inline void set_mode1curstage(::google::protobuf::int32 value);

  // optional int32 mode2curstage = 2;
  inline bool has_mode2curstage() const;
  inline void clear_mode2curstage();
  static const int kMode2CurstageFieldNumber = 2;
  inline ::google::protobuf::int32 mode2curstage() const;
  inline void set_mode2curstage(::google::protobuf::int32 value);

  // optional int32 teamanger = 3;
  inline bool has_teamanger() const;
  inline void clear_teamanger();
  static const int kTeamangerFieldNumber = 3;
  inline ::google::protobuf::int32 teamanger() const;
  inline void set_teamanger(::google::protobuf::int32 value);

  // optional int32 mode2chlgcnt = 4;
  inline bool has_mode2chlgcnt() const;
  inline void clear_mode2chlgcnt();
  static const int kMode2ChlgcntFieldNumber = 4;
  inline ::google::protobuf::int32 mode2chlgcnt() const;
  inline void set_mode2chlgcnt(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.NotifyExpeditionInfo)
 private:
  inline void set_has_mode1curstage();
  inline void clear_has_mode1curstage();
  inline void set_has_mode2curstage();
  inline void clear_has_mode2curstage();
  inline void set_has_teamanger();
  inline void clear_has_teamanger();
  inline void set_has_mode2chlgcnt();
  inline void clear_has_mode2chlgcnt();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 mode1curstage_;
  ::google::protobuf::int32 mode2curstage_;
  ::google::protobuf::int32 teamanger_;
  ::google::protobuf::int32 mode2chlgcnt_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_MessageNotifyExpeditionInfo_2eproto();
  friend void protobuf_AssignDesc_MessageNotifyExpeditionInfo_2eproto();
  friend void protobuf_ShutdownFile_MessageNotifyExpeditionInfo_2eproto();

  void InitAsDefaultInstance();
  static NotifyExpeditionInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// NotifyExpeditionInfo

// optional int32 mode1curstage = 1;
inline bool NotifyExpeditionInfo::has_mode1curstage() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NotifyExpeditionInfo::set_has_mode1curstage() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NotifyExpeditionInfo::clear_has_mode1curstage() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NotifyExpeditionInfo::clear_mode1curstage() {
  mode1curstage_ = 0;
  clear_has_mode1curstage();
}
inline ::google::protobuf::int32 NotifyExpeditionInfo::mode1curstage() const {
  return mode1curstage_;
}
inline void NotifyExpeditionInfo::set_mode1curstage(::google::protobuf::int32 value) {
  set_has_mode1curstage();
  mode1curstage_ = value;
}

// optional int32 mode2curstage = 2;
inline bool NotifyExpeditionInfo::has_mode2curstage() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NotifyExpeditionInfo::set_has_mode2curstage() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NotifyExpeditionInfo::clear_has_mode2curstage() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NotifyExpeditionInfo::clear_mode2curstage() {
  mode2curstage_ = 0;
  clear_has_mode2curstage();
}
inline ::google::protobuf::int32 NotifyExpeditionInfo::mode2curstage() const {
  return mode2curstage_;
}
inline void NotifyExpeditionInfo::set_mode2curstage(::google::protobuf::int32 value) {
  set_has_mode2curstage();
  mode2curstage_ = value;
}

// optional int32 teamanger = 3;
inline bool NotifyExpeditionInfo::has_teamanger() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NotifyExpeditionInfo::set_has_teamanger() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NotifyExpeditionInfo::clear_has_teamanger() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NotifyExpeditionInfo::clear_teamanger() {
  teamanger_ = 0;
  clear_has_teamanger();
}
inline ::google::protobuf::int32 NotifyExpeditionInfo::teamanger() const {
  return teamanger_;
}
inline void NotifyExpeditionInfo::set_teamanger(::google::protobuf::int32 value) {
  set_has_teamanger();
  teamanger_ = value;
}

// optional int32 mode2chlgcnt = 4;
inline bool NotifyExpeditionInfo::has_mode2chlgcnt() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NotifyExpeditionInfo::set_has_mode2chlgcnt() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NotifyExpeditionInfo::clear_has_mode2chlgcnt() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NotifyExpeditionInfo::clear_mode2chlgcnt() {
  mode2chlgcnt_ = 0;
  clear_has_mode2chlgcnt();
}
inline ::google::protobuf::int32 NotifyExpeditionInfo::mode2chlgcnt() const {
  return mode2chlgcnt_;
}
inline void NotifyExpeditionInfo::set_mode2chlgcnt(::google::protobuf::int32 value) {
  set_has_mode2chlgcnt();
  mode2chlgcnt_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageNotifyExpeditionInfo_2eproto__INCLUDED
