// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageAttackMonsterRequest.proto

#ifndef PROTOBUF_MessageAttackMonsterRequest_2eproto__INCLUDED
#define PROTOBUF_MessageAttackMonsterRequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageAttackMonsterRequest_2eproto();
void protobuf_AssignDesc_MessageAttackMonsterRequest_2eproto();
void protobuf_ShutdownFile_MessageAttackMonsterRequest_2eproto();

class AttackMonsterRequest;

// ===================================================================

class AttackMonsterRequest : public ::google::protobuf::Message {
 public:
  AttackMonsterRequest();
  virtual ~AttackMonsterRequest();

  AttackMonsterRequest(const AttackMonsterRequest& from);

  inline AttackMonsterRequest& operator=(const AttackMonsterRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AttackMonsterRequest& default_instance();

  void Swap(AttackMonsterRequest* other);

  // implements Message ----------------------------------------------

  AttackMonsterRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AttackMonsterRequest& from);
  void MergeFrom(const AttackMonsterRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 scene = 1;
  inline bool has_scene() const;
  inline void clear_scene();
  static const int kSceneFieldNumber = 1;
  inline ::google::protobuf::int32 scene() const;
  inline void set_scene(::google::protobuf::int32 value);

  // optional int32 monster = 2;
  inline bool has_monster() const;
  inline void clear_monster();
  static const int kMonsterFieldNumber = 2;
  inline ::google::protobuf::int32 monster() const;
  inline void set_monster(::google::protobuf::int32 value);

  // optional int32 type = 3;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional int32 engage = 4;
  inline bool has_engage() const;
  inline void clear_engage();
  static const int kEngageFieldNumber = 4;
  inline ::google::protobuf::int32 engage() const;
  inline void set_engage(::google::protobuf::int32 value);

  // optional int32 score = 5;
  inline bool has_score() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 5;
  inline ::google::protobuf::int32 score() const;
  inline void set_score(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.AttackMonsterRequest)
 private:
  inline void set_has_scene();
  inline void clear_has_scene();
  inline void set_has_monster();
  inline void clear_has_monster();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_engage();
  inline void clear_has_engage();
  inline void set_has_score();
  inline void clear_has_score();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 scene_;
  ::google::protobuf::int32 monster_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 engage_;
  ::google::protobuf::int32 score_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_MessageAttackMonsterRequest_2eproto();
  friend void protobuf_AssignDesc_MessageAttackMonsterRequest_2eproto();
  friend void protobuf_ShutdownFile_MessageAttackMonsterRequest_2eproto();

  void InitAsDefaultInstance();
  static AttackMonsterRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// AttackMonsterRequest

// optional int32 scene = 1;
inline bool AttackMonsterRequest::has_scene() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AttackMonsterRequest::set_has_scene() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AttackMonsterRequest::clear_has_scene() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AttackMonsterRequest::clear_scene() {
  scene_ = 0;
  clear_has_scene();
}
inline ::google::protobuf::int32 AttackMonsterRequest::scene() const {
  return scene_;
}
inline void AttackMonsterRequest::set_scene(::google::protobuf::int32 value) {
  set_has_scene();
  scene_ = value;
}

// optional int32 monster = 2;
inline bool AttackMonsterRequest::has_monster() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AttackMonsterRequest::set_has_monster() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AttackMonsterRequest::clear_has_monster() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AttackMonsterRequest::clear_monster() {
  monster_ = 0;
  clear_has_monster();
}
inline ::google::protobuf::int32 AttackMonsterRequest::monster() const {
  return monster_;
}
inline void AttackMonsterRequest::set_monster(::google::protobuf::int32 value) {
  set_has_monster();
  monster_ = value;
}

// optional int32 type = 3;
inline bool AttackMonsterRequest::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AttackMonsterRequest::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AttackMonsterRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AttackMonsterRequest::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 AttackMonsterRequest::type() const {
  return type_;
}
inline void AttackMonsterRequest::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// optional int32 engage = 4;
inline bool AttackMonsterRequest::has_engage() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AttackMonsterRequest::set_has_engage() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AttackMonsterRequest::clear_has_engage() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AttackMonsterRequest::clear_engage() {
  engage_ = 0;
  clear_has_engage();
}
inline ::google::protobuf::int32 AttackMonsterRequest::engage() const {
  return engage_;
}
inline void AttackMonsterRequest::set_engage(::google::protobuf::int32 value) {
  set_has_engage();
  engage_ = value;
}

// optional int32 score = 5;
inline bool AttackMonsterRequest::has_score() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AttackMonsterRequest::set_has_score() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AttackMonsterRequest::clear_has_score() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AttackMonsterRequest::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline ::google::protobuf::int32 AttackMonsterRequest::score() const {
  return score_;
}
inline void AttackMonsterRequest::set_score(::google::protobuf::int32 value) {
  set_has_score();
  score_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageAttackMonsterRequest_2eproto__INCLUDED
