// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagePlayerDataResponse.proto

#ifndef PROTOBUF_MessagePlayerDataResponse_2eproto__INCLUDED
#define PROTOBUF_MessagePlayerDataResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessagePlayerDataResponse_2eproto();
void protobuf_AssignDesc_MessagePlayerDataResponse_2eproto();
void protobuf_ShutdownFile_MessagePlayerDataResponse_2eproto();

class PlayerDataResponse;

// ===================================================================

class PlayerDataResponse : public ::google::protobuf::Message {
 public:
  PlayerDataResponse();
  virtual ~PlayerDataResponse();

  PlayerDataResponse(const PlayerDataResponse& from);

  inline PlayerDataResponse& operator=(const PlayerDataResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerDataResponse& default_instance();

  void Swap(PlayerDataResponse* other);

  // implements Message ----------------------------------------------

  PlayerDataResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerDataResponse& from);
  void MergeFrom(const PlayerDataResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 pid = 1;
  inline bool has_pid() const;
  inline void clear_pid();
  static const int kPidFieldNumber = 1;
  inline ::google::protobuf::int64 pid() const;
  inline void set_pid(::google::protobuf::int64 value);

  // optional int32 templateid = 2;
  inline bool has_templateid() const;
  inline void clear_templateid();
  static const int kTemplateidFieldNumber = 2;
  inline ::google::protobuf::int32 templateid() const;
  inline void set_templateid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.PlayerDataResponse)
 private:
  inline void set_has_pid();
  inline void clear_has_pid();
  inline void set_has_templateid();
  inline void clear_has_templateid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 pid_;
  ::google::protobuf::int32 templateid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_MessagePlayerDataResponse_2eproto();
  friend void protobuf_AssignDesc_MessagePlayerDataResponse_2eproto();
  friend void protobuf_ShutdownFile_MessagePlayerDataResponse_2eproto();

  void InitAsDefaultInstance();
  static PlayerDataResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// PlayerDataResponse

// optional int64 pid = 1;
inline bool PlayerDataResponse::has_pid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerDataResponse::set_has_pid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerDataResponse::clear_has_pid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerDataResponse::clear_pid() {
  pid_ = GOOGLE_LONGLONG(0);
  clear_has_pid();
}
inline ::google::protobuf::int64 PlayerDataResponse::pid() const {
  return pid_;
}
inline void PlayerDataResponse::set_pid(::google::protobuf::int64 value) {
  set_has_pid();
  pid_ = value;
}

// optional int32 templateid = 2;
inline bool PlayerDataResponse::has_templateid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayerDataResponse::set_has_templateid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayerDataResponse::clear_has_templateid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayerDataResponse::clear_templateid() {
  templateid_ = 0;
  clear_has_templateid();
}
inline ::google::protobuf::int32 PlayerDataResponse::templateid() const {
  return templateid_;
}
inline void PlayerDataResponse::set_templateid(::google::protobuf::int32 value) {
  set_has_templateid();
  templateid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessagePlayerDataResponse_2eproto__INCLUDED
