// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageTaskAddNotify.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageTaskAddNotify.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Message {

namespace {

const ::google::protobuf::Descriptor* TaskAddNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TaskAddNotify_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageTaskAddNotify_2eproto() {
  protobuf_AddDesc_MessageTaskAddNotify_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageTaskAddNotify.proto");
  GOOGLE_CHECK(file != NULL);
  TaskAddNotify_descriptor_ = file->message_type(0);
  static const int TaskAddNotify_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TaskAddNotify, tasks_),
  };
  TaskAddNotify_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TaskAddNotify_descriptor_,
      TaskAddNotify::default_instance_,
      TaskAddNotify_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TaskAddNotify, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TaskAddNotify, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TaskAddNotify));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageTaskAddNotify_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TaskAddNotify_descriptor_, &TaskAddNotify::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageTaskAddNotify_2eproto() {
  delete TaskAddNotify::default_instance_;
  delete TaskAddNotify_reflection_;
}

void protobuf_AddDesc_MessageTaskAddNotify_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Message::protobuf_AddDesc_MessageTaskSync_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032MessageTaskAddNotify.proto\022\007Message\032\025M"
    "essageTaskSync.proto\"-\n\rTaskAddNotify\022\034\n"
    "\005tasks\030\001 \003(\0132\r.Message.Task", 107);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageTaskAddNotify.proto", &protobuf_RegisterTypes);
  TaskAddNotify::default_instance_ = new TaskAddNotify();
  TaskAddNotify::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageTaskAddNotify_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageTaskAddNotify_2eproto {
  StaticDescriptorInitializer_MessageTaskAddNotify_2eproto() {
    protobuf_AddDesc_MessageTaskAddNotify_2eproto();
  }
} static_descriptor_initializer_MessageTaskAddNotify_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int TaskAddNotify::kTasksFieldNumber;
#endif  // !_MSC_VER

TaskAddNotify::TaskAddNotify()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TaskAddNotify::InitAsDefaultInstance() {
}

TaskAddNotify::TaskAddNotify(const TaskAddNotify& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TaskAddNotify::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TaskAddNotify::~TaskAddNotify() {
  SharedDtor();
}

void TaskAddNotify::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TaskAddNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TaskAddNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TaskAddNotify_descriptor_;
}

const TaskAddNotify& TaskAddNotify::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageTaskAddNotify_2eproto();
  return *default_instance_;
}

TaskAddNotify* TaskAddNotify::default_instance_ = NULL;

TaskAddNotify* TaskAddNotify::New() const {
  return new TaskAddNotify;
}

void TaskAddNotify::Clear() {
  tasks_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TaskAddNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Message.Task tasks = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_tasks:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_tasks()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_tasks;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TaskAddNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .Message.Task tasks = 1;
  for (int i = 0; i < this->tasks_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->tasks(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TaskAddNotify::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .Message.Task tasks = 1;
  for (int i = 0; i < this->tasks_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->tasks(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TaskAddNotify::ByteSize() const {
  int total_size = 0;

  // repeated .Message.Task tasks = 1;
  total_size += 1 * this->tasks_size();
  for (int i = 0; i < this->tasks_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->tasks(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TaskAddNotify::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TaskAddNotify* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TaskAddNotify*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TaskAddNotify::MergeFrom(const TaskAddNotify& from) {
  GOOGLE_CHECK_NE(&from, this);
  tasks_.MergeFrom(from.tasks_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TaskAddNotify::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TaskAddNotify::CopyFrom(const TaskAddNotify& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TaskAddNotify::IsInitialized() const {

  for (int i = 0; i < tasks_size(); i++) {
    if (!this->tasks(i).IsInitialized()) return false;
  }
  return true;
}

void TaskAddNotify::Swap(TaskAddNotify* other) {
  if (other != this) {
    tasks_.Swap(&other->tasks_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TaskAddNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TaskAddNotify_descriptor_;
  metadata.reflection = TaskAddNotify_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

// @@protoc_insertion_point(global_scope)
