// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageErrorNo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageErrorNo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Message {

namespace {

const ::google::protobuf::Descriptor* ErrorNo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ErrorNo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageErrorNo_2eproto() {
  protobuf_AddDesc_MessageErrorNo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageErrorNo.proto");
  GOOGLE_CHECK(file != NULL);
  ErrorNo_descriptor_ = file->message_type(0);
  static const int ErrorNo_offsets_[12] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, error_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, userid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, paramint1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, paramint2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, paramint3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, paramlong1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, paramlong2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, paramlong3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, paramstr1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, paramstr2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, paramstr3_),
  };
  ErrorNo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ErrorNo_descriptor_,
      ErrorNo::default_instance_,
      ErrorNo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorNo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ErrorNo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageErrorNo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ErrorNo_descriptor_, &ErrorNo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageErrorNo_2eproto() {
  delete ErrorNo::default_instance_;
  delete ErrorNo_reflection_;
}

void protobuf_AddDesc_MessageErrorNo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024MessageErrorNo.proto\022\007Message\"\344\001\n\007Erro"
    "rNo\022\r\n\005error\030\001 \001(\005\022\016\n\006userid\030\002 \001(\003\022\014\n\004ty"
    "pe\030\003 \001(\005\022\021\n\tparamint1\030\004 \001(\005\022\021\n\tparamint2"
    "\030\005 \001(\005\022\021\n\tparamint3\030\006 \001(\005\022\022\n\nparamlong1\030"
    "\007 \001(\003\022\022\n\nparamlong2\030\010 \001(\003\022\022\n\nparamlong3\030"
    "\t \001(\003\022\021\n\tparamstr1\030\n \001(\t\022\021\n\tparamstr2\030\013 "
    "\001(\t\022\021\n\tparamstr3\030\014 \001(\t", 262);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageErrorNo.proto", &protobuf_RegisterTypes);
  ErrorNo::default_instance_ = new ErrorNo();
  ErrorNo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageErrorNo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageErrorNo_2eproto {
  StaticDescriptorInitializer_MessageErrorNo_2eproto() {
    protobuf_AddDesc_MessageErrorNo_2eproto();
  }
} static_descriptor_initializer_MessageErrorNo_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ErrorNo::kErrorFieldNumber;
const int ErrorNo::kUseridFieldNumber;
const int ErrorNo::kTypeFieldNumber;
const int ErrorNo::kParamint1FieldNumber;
const int ErrorNo::kParamint2FieldNumber;
const int ErrorNo::kParamint3FieldNumber;
const int ErrorNo::kParamlong1FieldNumber;
const int ErrorNo::kParamlong2FieldNumber;
const int ErrorNo::kParamlong3FieldNumber;
const int ErrorNo::kParamstr1FieldNumber;
const int ErrorNo::kParamstr2FieldNumber;
const int ErrorNo::kParamstr3FieldNumber;
#endif  // !_MSC_VER

ErrorNo::ErrorNo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ErrorNo::InitAsDefaultInstance() {
}

ErrorNo::ErrorNo(const ErrorNo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ErrorNo::SharedCtor() {
  _cached_size_ = 0;
  error_ = 0;
  userid_ = GOOGLE_LONGLONG(0);
  type_ = 0;
  paramint1_ = 0;
  paramint2_ = 0;
  paramint3_ = 0;
  paramlong1_ = GOOGLE_LONGLONG(0);
  paramlong2_ = GOOGLE_LONGLONG(0);
  paramlong3_ = GOOGLE_LONGLONG(0);
  paramstr1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  paramstr2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  paramstr3_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ErrorNo::~ErrorNo() {
  SharedDtor();
}

void ErrorNo::SharedDtor() {
  if (paramstr1_ != &::google::protobuf::internal::kEmptyString) {
    delete paramstr1_;
  }
  if (paramstr2_ != &::google::protobuf::internal::kEmptyString) {
    delete paramstr2_;
  }
  if (paramstr3_ != &::google::protobuf::internal::kEmptyString) {
    delete paramstr3_;
  }
  if (this != default_instance_) {
  }
}

void ErrorNo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ErrorNo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ErrorNo_descriptor_;
}

const ErrorNo& ErrorNo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageErrorNo_2eproto();
  return *default_instance_;
}

ErrorNo* ErrorNo::default_instance_ = NULL;

ErrorNo* ErrorNo::New() const {
  return new ErrorNo;
}

void ErrorNo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    error_ = 0;
    userid_ = GOOGLE_LONGLONG(0);
    type_ = 0;
    paramint1_ = 0;
    paramint2_ = 0;
    paramint3_ = 0;
    paramlong1_ = GOOGLE_LONGLONG(0);
    paramlong2_ = GOOGLE_LONGLONG(0);
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    paramlong3_ = GOOGLE_LONGLONG(0);
    if (has_paramstr1()) {
      if (paramstr1_ != &::google::protobuf::internal::kEmptyString) {
        paramstr1_->clear();
      }
    }
    if (has_paramstr2()) {
      if (paramstr2_ != &::google::protobuf::internal::kEmptyString) {
        paramstr2_->clear();
      }
    }
    if (has_paramstr3()) {
      if (paramstr3_ != &::google::protobuf::internal::kEmptyString) {
        paramstr3_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ErrorNo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 error = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
          set_has_error();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_userid;
        break;
      }

      // optional int64 userid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_userid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &userid_)));
          set_has_userid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_type;
        break;
      }

      // optional int32 type = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_paramint1;
        break;
      }

      // optional int32 paramint1 = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_paramint1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &paramint1_)));
          set_has_paramint1();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_paramint2;
        break;
      }

      // optional int32 paramint2 = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_paramint2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &paramint2_)));
          set_has_paramint2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_paramint3;
        break;
      }

      // optional int32 paramint3 = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_paramint3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &paramint3_)));
          set_has_paramint3();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_paramlong1;
        break;
      }

      // optional int64 paramlong1 = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_paramlong1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &paramlong1_)));
          set_has_paramlong1();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_paramlong2;
        break;
      }

      // optional int64 paramlong2 = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_paramlong2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &paramlong2_)));
          set_has_paramlong2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_paramlong3;
        break;
      }

      // optional int64 paramlong3 = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_paramlong3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &paramlong3_)));
          set_has_paramlong3();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(82)) goto parse_paramstr1;
        break;
      }

      // optional string paramstr1 = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_paramstr1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_paramstr1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->paramstr1().data(), this->paramstr1().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_paramstr2;
        break;
      }

      // optional string paramstr2 = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_paramstr2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_paramstr2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->paramstr2().data(), this->paramstr2().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(98)) goto parse_paramstr3;
        break;
      }

      // optional string paramstr3 = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_paramstr3:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_paramstr3()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->paramstr3().data(), this->paramstr3().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ErrorNo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 error = 1;
  if (has_error()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error(), output);
  }

  // optional int64 userid = 2;
  if (has_userid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->userid(), output);
  }

  // optional int32 type = 3;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->type(), output);
  }

  // optional int32 paramint1 = 4;
  if (has_paramint1()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->paramint1(), output);
  }

  // optional int32 paramint2 = 5;
  if (has_paramint2()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->paramint2(), output);
  }

  // optional int32 paramint3 = 6;
  if (has_paramint3()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->paramint3(), output);
  }

  // optional int64 paramlong1 = 7;
  if (has_paramlong1()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->paramlong1(), output);
  }

  // optional int64 paramlong2 = 8;
  if (has_paramlong2()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->paramlong2(), output);
  }

  // optional int64 paramlong3 = 9;
  if (has_paramlong3()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(9, this->paramlong3(), output);
  }

  // optional string paramstr1 = 10;
  if (has_paramstr1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->paramstr1().data(), this->paramstr1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      10, this->paramstr1(), output);
  }

  // optional string paramstr2 = 11;
  if (has_paramstr2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->paramstr2().data(), this->paramstr2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      11, this->paramstr2(), output);
  }

  // optional string paramstr3 = 12;
  if (has_paramstr3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->paramstr3().data(), this->paramstr3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      12, this->paramstr3(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ErrorNo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 error = 1;
  if (has_error()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->error(), target);
  }

  // optional int64 userid = 2;
  if (has_userid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->userid(), target);
  }

  // optional int32 type = 3;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->type(), target);
  }

  // optional int32 paramint1 = 4;
  if (has_paramint1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->paramint1(), target);
  }

  // optional int32 paramint2 = 5;
  if (has_paramint2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->paramint2(), target);
  }

  // optional int32 paramint3 = 6;
  if (has_paramint3()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->paramint3(), target);
  }

  // optional int64 paramlong1 = 7;
  if (has_paramlong1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->paramlong1(), target);
  }

  // optional int64 paramlong2 = 8;
  if (has_paramlong2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->paramlong2(), target);
  }

  // optional int64 paramlong3 = 9;
  if (has_paramlong3()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(9, this->paramlong3(), target);
  }

  // optional string paramstr1 = 10;
  if (has_paramstr1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->paramstr1().data(), this->paramstr1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->paramstr1(), target);
  }

  // optional string paramstr2 = 11;
  if (has_paramstr2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->paramstr2().data(), this->paramstr2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->paramstr2(), target);
  }

  // optional string paramstr3 = 12;
  if (has_paramstr3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->paramstr3().data(), this->paramstr3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->paramstr3(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ErrorNo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 error = 1;
    if (has_error()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->error());
    }

    // optional int64 userid = 2;
    if (has_userid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->userid());
    }

    // optional int32 type = 3;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

    // optional int32 paramint1 = 4;
    if (has_paramint1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->paramint1());
    }

    // optional int32 paramint2 = 5;
    if (has_paramint2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->paramint2());
    }

    // optional int32 paramint3 = 6;
    if (has_paramint3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->paramint3());
    }

    // optional int64 paramlong1 = 7;
    if (has_paramlong1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->paramlong1());
    }

    // optional int64 paramlong2 = 8;
    if (has_paramlong2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->paramlong2());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional int64 paramlong3 = 9;
    if (has_paramlong3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->paramlong3());
    }

    // optional string paramstr1 = 10;
    if (has_paramstr1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->paramstr1());
    }

    // optional string paramstr2 = 11;
    if (has_paramstr2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->paramstr2());
    }

    // optional string paramstr3 = 12;
    if (has_paramstr3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->paramstr3());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ErrorNo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ErrorNo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ErrorNo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ErrorNo::MergeFrom(const ErrorNo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_error()) {
      set_error(from.error());
    }
    if (from.has_userid()) {
      set_userid(from.userid());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_paramint1()) {
      set_paramint1(from.paramint1());
    }
    if (from.has_paramint2()) {
      set_paramint2(from.paramint2());
    }
    if (from.has_paramint3()) {
      set_paramint3(from.paramint3());
    }
    if (from.has_paramlong1()) {
      set_paramlong1(from.paramlong1());
    }
    if (from.has_paramlong2()) {
      set_paramlong2(from.paramlong2());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_paramlong3()) {
      set_paramlong3(from.paramlong3());
    }
    if (from.has_paramstr1()) {
      set_paramstr1(from.paramstr1());
    }
    if (from.has_paramstr2()) {
      set_paramstr2(from.paramstr2());
    }
    if (from.has_paramstr3()) {
      set_paramstr3(from.paramstr3());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ErrorNo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ErrorNo::CopyFrom(const ErrorNo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ErrorNo::IsInitialized() const {

  return true;
}

void ErrorNo::Swap(ErrorNo* other) {
  if (other != this) {
    std::swap(error_, other->error_);
    std::swap(userid_, other->userid_);
    std::swap(type_, other->type_);
    std::swap(paramint1_, other->paramint1_);
    std::swap(paramint2_, other->paramint2_);
    std::swap(paramint3_, other->paramint3_);
    std::swap(paramlong1_, other->paramlong1_);
    std::swap(paramlong2_, other->paramlong2_);
    std::swap(paramlong3_, other->paramlong3_);
    std::swap(paramstr1_, other->paramstr1_);
    std::swap(paramstr2_, other->paramstr2_);
    std::swap(paramstr3_, other->paramstr3_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ErrorNo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ErrorNo_descriptor_;
  metadata.reflection = ErrorNo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

// @@protoc_insertion_point(global_scope)
