// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageFightAward.proto

#ifndef PROTOBUF_MessageFightAward_2eproto__INCLUDED
#define PROTOBUF_MessageFightAward_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageFightAward_2eproto();
void protobuf_AssignDesc_MessageFightAward_2eproto();
void protobuf_ShutdownFile_MessageFightAward_2eproto();

class FightAward;

// ===================================================================

class FightAward : public ::google::protobuf::Message {
 public:
  FightAward();
  virtual ~FightAward();

  FightAward(const FightAward& from);

  inline FightAward& operator=(const FightAward& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FightAward& default_instance();

  void Swap(FightAward* other);

  // implements Message ----------------------------------------------

  FightAward* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FightAward& from);
  void MergeFrom(const FightAward& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 silver = 1;
  inline bool has_silver() const;
  inline void clear_silver();
  static const int kSilverFieldNumber = 1;
  inline ::google::protobuf::int32 silver() const;
  inline void set_silver(::google::protobuf::int32 value);

  // optional int32 exp = 2;
  inline bool has_exp() const;
  inline void clear_exp();
  static const int kExpFieldNumber = 2;
  inline ::google::protobuf::int32 exp() const;
  inline void set_exp(::google::protobuf::int32 value);

  // optional int32 totalsilver = 3;
  inline bool has_totalsilver() const;
  inline void clear_totalsilver();
  static const int kTotalsilverFieldNumber = 3;
  inline ::google::protobuf::int32 totalsilver() const;
  inline void set_totalsilver(::google::protobuf::int32 value);

  // optional int32 totalexp = 4;
  inline bool has_totalexp() const;
  inline void clear_totalexp();
  static const int kTotalexpFieldNumber = 4;
  inline ::google::protobuf::int32 totalexp() const;
  inline void set_totalexp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.FightAward)
 private:
  inline void set_has_silver();
  inline void clear_has_silver();
  inline void set_has_exp();
  inline void clear_has_exp();
  inline void set_has_totalsilver();
  inline void clear_has_totalsilver();
  inline void set_has_totalexp();
  inline void clear_has_totalexp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 silver_;
  ::google::protobuf::int32 exp_;
  ::google::protobuf::int32 totalsilver_;
  ::google::protobuf::int32 totalexp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_MessageFightAward_2eproto();
  friend void protobuf_AssignDesc_MessageFightAward_2eproto();
  friend void protobuf_ShutdownFile_MessageFightAward_2eproto();

  void InitAsDefaultInstance();
  static FightAward* default_instance_;
};
// ===================================================================


// ===================================================================

// FightAward

// optional int32 silver = 1;
inline bool FightAward::has_silver() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FightAward::set_has_silver() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FightAward::clear_has_silver() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FightAward::clear_silver() {
  silver_ = 0;
  clear_has_silver();
}
inline ::google::protobuf::int32 FightAward::silver() const {
  return silver_;
}
inline void FightAward::set_silver(::google::protobuf::int32 value) {
  set_has_silver();
  silver_ = value;
}

// optional int32 exp = 2;
inline bool FightAward::has_exp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FightAward::set_has_exp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FightAward::clear_has_exp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FightAward::clear_exp() {
  exp_ = 0;
  clear_has_exp();
}
inline ::google::protobuf::int32 FightAward::exp() const {
  return exp_;
}
inline void FightAward::set_exp(::google::protobuf::int32 value) {
  set_has_exp();
  exp_ = value;
}

// optional int32 totalsilver = 3;
inline bool FightAward::has_totalsilver() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FightAward::set_has_totalsilver() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FightAward::clear_has_totalsilver() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FightAward::clear_totalsilver() {
  totalsilver_ = 0;
  clear_has_totalsilver();
}
inline ::google::protobuf::int32 FightAward::totalsilver() const {
  return totalsilver_;
}
inline void FightAward::set_totalsilver(::google::protobuf::int32 value) {
  set_has_totalsilver();
  totalsilver_ = value;
}

// optional int32 totalexp = 4;
inline bool FightAward::has_totalexp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void FightAward::set_has_totalexp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void FightAward::clear_has_totalexp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void FightAward::clear_totalexp() {
  totalexp_ = 0;
  clear_has_totalexp();
}
inline ::google::protobuf::int32 FightAward::totalexp() const {
  return totalexp_;
}
inline void FightAward::set_totalexp(::google::protobuf::int32 value) {
  set_has_totalexp();
  totalexp_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageFightAward_2eproto__INCLUDED
