// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageWorldDataRequest.proto

#ifndef PROTOBUF_MessageWorldDataRequest_2eproto__INCLUDED
#define PROTOBUF_MessageWorldDataRequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageWorldDataRequest_2eproto();
void protobuf_AssignDesc_MessageWorldDataRequest_2eproto();
void protobuf_ShutdownFile_MessageWorldDataRequest_2eproto();

class WorldDataRequest;

// ===================================================================

class WorldDataRequest : public ::google::protobuf::Message {
 public:
  WorldDataRequest();
  virtual ~WorldDataRequest();

  WorldDataRequest(const WorldDataRequest& from);

  inline WorldDataRequest& operator=(const WorldDataRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorldDataRequest& default_instance();

  void Swap(WorldDataRequest* other);

  // implements Message ----------------------------------------------

  WorldDataRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorldDataRequest& from);
  void MergeFrom(const WorldDataRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 world = 1;
  inline bool has_world() const;
  inline void clear_world();
  static const int kWorldFieldNumber = 1;
  inline ::google::protobuf::int32 world() const;
  inline void set_world(::google::protobuf::int32 value);

  // optional int32 server = 2;
  inline bool has_server() const;
  inline void clear_server();
  static const int kServerFieldNumber = 2;
  inline ::google::protobuf::int32 server() const;
  inline void set_server(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.WorldDataRequest)
 private:
  inline void set_has_world();
  inline void clear_has_world();
  inline void set_has_server();
  inline void clear_has_server();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 world_;
  ::google::protobuf::int32 server_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_MessageWorldDataRequest_2eproto();
  friend void protobuf_AssignDesc_MessageWorldDataRequest_2eproto();
  friend void protobuf_ShutdownFile_MessageWorldDataRequest_2eproto();

  void InitAsDefaultInstance();
  static WorldDataRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// WorldDataRequest

// optional int32 world = 1;
inline bool WorldDataRequest::has_world() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorldDataRequest::set_has_world() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorldDataRequest::clear_has_world() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorldDataRequest::clear_world() {
  world_ = 0;
  clear_has_world();
}
inline ::google::protobuf::int32 WorldDataRequest::world() const {
  return world_;
}
inline void WorldDataRequest::set_world(::google::protobuf::int32 value) {
  set_has_world();
  world_ = value;
}

// optional int32 server = 2;
inline bool WorldDataRequest::has_server() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WorldDataRequest::set_has_server() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WorldDataRequest::clear_has_server() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WorldDataRequest::clear_server() {
  server_ = 0;
  clear_has_server();
}
inline ::google::protobuf::int32 WorldDataRequest::server() const {
  return server_;
}
inline void WorldDataRequest::set_server(::google::protobuf::int32 value) {
  set_has_server();
  server_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageWorldDataRequest_2eproto__INCLUDED
