// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageItem.proto

#ifndef PROTOBUF_MessageItem_2eproto__INCLUDED
#define PROTOBUF_MessageItem_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageItem_2eproto();
void protobuf_AssignDesc_MessageItem_2eproto();
void protobuf_ShutdownFile_MessageItem_2eproto();

class ItemGainSync;
class ItemDeleteSync;
class ItemUseRequest;
class ItemDeleteRequest;
class ItemSellRequest;
class ItemEquipRequest;
class ItemUnequipRequest;
class ItemAttrSync;
class ItemAttrSync_Attr;

// ===================================================================

class ItemGainSync : public ::google::protobuf::Message {
 public:
  ItemGainSync();
  virtual ~ItemGainSync();

  ItemGainSync(const ItemGainSync& from);

  inline ItemGainSync& operator=(const ItemGainSync& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemGainSync& default_instance();

  void Swap(ItemGainSync* other);

  // implements Message ----------------------------------------------

  ItemGainSync* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemGainSync& from);
  void MergeFrom(const ItemGainSync& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 itemid = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 1;
  inline ::google::protobuf::int64 itemid() const;
  inline void set_itemid(::google::protobuf::int64 value);

  // optional int32 templateid = 2;
  inline bool has_templateid() const;
  inline void clear_templateid();
  static const int kTemplateidFieldNumber = 2;
  inline ::google::protobuf::int32 templateid() const;
  inline void set_templateid(::google::protobuf::int32 value);

  // optional int32 stack = 3;
  inline bool has_stack() const;
  inline void clear_stack();
  static const int kStackFieldNumber = 3;
  inline ::google::protobuf::int32 stack() const;
  inline void set_stack(::google::protobuf::int32 value);

  // optional int32 position = 4;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 4;
  inline ::google::protobuf::int32 position() const;
  inline void set_position(::google::protobuf::int32 value);

  // optional int64 parent = 5;
  inline bool has_parent() const;
  inline void clear_parent();
  static const int kParentFieldNumber = 5;
  inline ::google::protobuf::int64 parent() const;
  inline void set_parent(::google::protobuf::int64 value);

  // optional int64 equipid = 6;
  inline bool has_equipid() const;
  inline void clear_equipid();
  static const int kEquipidFieldNumber = 6;
  inline ::google::protobuf::int64 equipid() const;
  inline void set_equipid(::google::protobuf::int64 value);

  // optional int32 intensify = 7;
  inline bool has_intensify() const;
  inline void clear_intensify();
  static const int kIntensifyFieldNumber = 7;
  inline ::google::protobuf::int32 intensify() const;
  inline void set_intensify(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.ItemGainSync)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_templateid();
  inline void clear_has_templateid();
  inline void set_has_stack();
  inline void clear_has_stack();
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_parent();
  inline void clear_has_parent();
  inline void set_has_equipid();
  inline void clear_has_equipid();
  inline void set_has_intensify();
  inline void clear_has_intensify();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 itemid_;
  ::google::protobuf::int32 templateid_;
  ::google::protobuf::int32 stack_;
  ::google::protobuf::int64 parent_;
  ::google::protobuf::int32 position_;
  ::google::protobuf::int32 intensify_;
  ::google::protobuf::int64 equipid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItem_2eproto();
  friend void protobuf_AssignDesc_MessageItem_2eproto();
  friend void protobuf_ShutdownFile_MessageItem_2eproto();

  void InitAsDefaultInstance();
  static ItemGainSync* default_instance_;
};
// -------------------------------------------------------------------

class ItemDeleteSync : public ::google::protobuf::Message {
 public:
  ItemDeleteSync();
  virtual ~ItemDeleteSync();

  ItemDeleteSync(const ItemDeleteSync& from);

  inline ItemDeleteSync& operator=(const ItemDeleteSync& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemDeleteSync& default_instance();

  void Swap(ItemDeleteSync* other);

  // implements Message ----------------------------------------------

  ItemDeleteSync* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemDeleteSync& from);
  void MergeFrom(const ItemDeleteSync& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 itemid = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 1;
  inline ::google::protobuf::int64 itemid() const;
  inline void set_itemid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Message.ItemDeleteSync)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 itemid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItem_2eproto();
  friend void protobuf_AssignDesc_MessageItem_2eproto();
  friend void protobuf_ShutdownFile_MessageItem_2eproto();

  void InitAsDefaultInstance();
  static ItemDeleteSync* default_instance_;
};
// -------------------------------------------------------------------

class ItemUseRequest : public ::google::protobuf::Message {
 public:
  ItemUseRequest();
  virtual ~ItemUseRequest();

  ItemUseRequest(const ItemUseRequest& from);

  inline ItemUseRequest& operator=(const ItemUseRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemUseRequest& default_instance();

  void Swap(ItemUseRequest* other);

  // implements Message ----------------------------------------------

  ItemUseRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemUseRequest& from);
  void MergeFrom(const ItemUseRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 itemid = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 1;
  inline ::google::protobuf::int64 itemid() const;
  inline void set_itemid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Message.ItemUseRequest)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 itemid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItem_2eproto();
  friend void protobuf_AssignDesc_MessageItem_2eproto();
  friend void protobuf_ShutdownFile_MessageItem_2eproto();

  void InitAsDefaultInstance();
  static ItemUseRequest* default_instance_;
};
// -------------------------------------------------------------------

class ItemDeleteRequest : public ::google::protobuf::Message {
 public:
  ItemDeleteRequest();
  virtual ~ItemDeleteRequest();

  ItemDeleteRequest(const ItemDeleteRequest& from);

  inline ItemDeleteRequest& operator=(const ItemDeleteRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemDeleteRequest& default_instance();

  void Swap(ItemDeleteRequest* other);

  // implements Message ----------------------------------------------

  ItemDeleteRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemDeleteRequest& from);
  void MergeFrom(const ItemDeleteRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 itemid = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 1;
  inline ::google::protobuf::int64 itemid() const;
  inline void set_itemid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Message.ItemDeleteRequest)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 itemid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItem_2eproto();
  friend void protobuf_AssignDesc_MessageItem_2eproto();
  friend void protobuf_ShutdownFile_MessageItem_2eproto();

  void InitAsDefaultInstance();
  static ItemDeleteRequest* default_instance_;
};
// -------------------------------------------------------------------

class ItemSellRequest : public ::google::protobuf::Message {
 public:
  ItemSellRequest();
  virtual ~ItemSellRequest();

  ItemSellRequest(const ItemSellRequest& from);

  inline ItemSellRequest& operator=(const ItemSellRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemSellRequest& default_instance();

  void Swap(ItemSellRequest* other);

  // implements Message ----------------------------------------------

  ItemSellRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemSellRequest& from);
  void MergeFrom(const ItemSellRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 itemid = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 1;
  inline ::google::protobuf::int64 itemid() const;
  inline void set_itemid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Message.ItemSellRequest)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 itemid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItem_2eproto();
  friend void protobuf_AssignDesc_MessageItem_2eproto();
  friend void protobuf_ShutdownFile_MessageItem_2eproto();

  void InitAsDefaultInstance();
  static ItemSellRequest* default_instance_;
};
// -------------------------------------------------------------------

class ItemEquipRequest : public ::google::protobuf::Message {
 public:
  ItemEquipRequest();
  virtual ~ItemEquipRequest();

  ItemEquipRequest(const ItemEquipRequest& from);

  inline ItemEquipRequest& operator=(const ItemEquipRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemEquipRequest& default_instance();

  void Swap(ItemEquipRequest* other);

  // implements Message ----------------------------------------------

  ItemEquipRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemEquipRequest& from);
  void MergeFrom(const ItemEquipRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 itemid = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 1;
  inline ::google::protobuf::int64 itemid() const;
  inline void set_itemid(::google::protobuf::int64 value);

  // optional int64 roleid = 2;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleidFieldNumber = 2;
  inline ::google::protobuf::int64 roleid() const;
  inline void set_roleid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Message.ItemEquipRequest)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_roleid();
  inline void clear_has_roleid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 itemid_;
  ::google::protobuf::int64 roleid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItem_2eproto();
  friend void protobuf_AssignDesc_MessageItem_2eproto();
  friend void protobuf_ShutdownFile_MessageItem_2eproto();

  void InitAsDefaultInstance();
  static ItemEquipRequest* default_instance_;
};
// -------------------------------------------------------------------

class ItemUnequipRequest : public ::google::protobuf::Message {
 public:
  ItemUnequipRequest();
  virtual ~ItemUnequipRequest();

  ItemUnequipRequest(const ItemUnequipRequest& from);

  inline ItemUnequipRequest& operator=(const ItemUnequipRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemUnequipRequest& default_instance();

  void Swap(ItemUnequipRequest* other);

  // implements Message ----------------------------------------------

  ItemUnequipRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemUnequipRequest& from);
  void MergeFrom(const ItemUnequipRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 itemid = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 1;
  inline ::google::protobuf::int64 itemid() const;
  inline void set_itemid(::google::protobuf::int64 value);

  // optional int64 roleid = 2;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleidFieldNumber = 2;
  inline ::google::protobuf::int64 roleid() const;
  inline void set_roleid(::google::protobuf::int64 value);

  // optional int32 position = 3;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 3;
  inline ::google::protobuf::int32 position() const;
  inline void set_position(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.ItemUnequipRequest)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_position();
  inline void clear_has_position();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 itemid_;
  ::google::protobuf::int64 roleid_;
  ::google::protobuf::int32 position_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItem_2eproto();
  friend void protobuf_AssignDesc_MessageItem_2eproto();
  friend void protobuf_ShutdownFile_MessageItem_2eproto();

  void InitAsDefaultInstance();
  static ItemUnequipRequest* default_instance_;
};
// -------------------------------------------------------------------

class ItemAttrSync_Attr : public ::google::protobuf::Message {
 public:
  ItemAttrSync_Attr();
  virtual ~ItemAttrSync_Attr();

  ItemAttrSync_Attr(const ItemAttrSync_Attr& from);

  inline ItemAttrSync_Attr& operator=(const ItemAttrSync_Attr& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemAttrSync_Attr& default_instance();

  void Swap(ItemAttrSync_Attr* other);

  // implements Message ----------------------------------------------

  ItemAttrSync_Attr* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemAttrSync_Attr& from);
  void MergeFrom(const ItemAttrSync_Attr& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional string group = 2;
  inline bool has_group() const;
  inline void clear_group();
  static const int kGroupFieldNumber = 2;
  inline const ::std::string& group() const;
  inline void set_group(const ::std::string& value);
  inline void set_group(const char* value);
  inline void set_group(const char* value, size_t size);
  inline ::std::string* mutable_group();
  inline ::std::string* release_group();
  inline void set_allocated_group(::std::string* group);

  // optional string key = 3;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 3;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const char* value, size_t size);
  inline ::std::string* mutable_key();
  inline ::std::string* release_key();
  inline void set_allocated_key(::std::string* key);

  // optional int32 val32 = 4;
  inline bool has_val32() const;
  inline void clear_val32();
  static const int kVal32FieldNumber = 4;
  inline ::google::protobuf::int32 val32() const;
  inline void set_val32(::google::protobuf::int32 value);

  // optional int64 val64 = 5;
  inline bool has_val64() const;
  inline void clear_val64();
  static const int kVal64FieldNumber = 5;
  inline ::google::protobuf::int64 val64() const;
  inline void set_val64(::google::protobuf::int64 value);

  // optional string valstr = 6;
  inline bool has_valstr() const;
  inline void clear_valstr();
  static const int kValstrFieldNumber = 6;
  inline const ::std::string& valstr() const;
  inline void set_valstr(const ::std::string& value);
  inline void set_valstr(const char* value);
  inline void set_valstr(const char* value, size_t size);
  inline ::std::string* mutable_valstr();
  inline ::std::string* release_valstr();
  inline void set_allocated_valstr(::std::string* valstr);

  // @@protoc_insertion_point(class_scope:Message.ItemAttrSync.Attr)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_group();
  inline void clear_has_group();
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_val32();
  inline void clear_has_val32();
  inline void set_has_val64();
  inline void clear_has_val64();
  inline void set_has_valstr();
  inline void clear_has_valstr();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* group_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 val32_;
  ::std::string* key_;
  ::google::protobuf::int64 val64_;
  ::std::string* valstr_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItem_2eproto();
  friend void protobuf_AssignDesc_MessageItem_2eproto();
  friend void protobuf_ShutdownFile_MessageItem_2eproto();

  void InitAsDefaultInstance();
  static ItemAttrSync_Attr* default_instance_;
};
// -------------------------------------------------------------------

class ItemAttrSync : public ::google::protobuf::Message {
 public:
  ItemAttrSync();
  virtual ~ItemAttrSync();

  ItemAttrSync(const ItemAttrSync& from);

  inline ItemAttrSync& operator=(const ItemAttrSync& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemAttrSync& default_instance();

  void Swap(ItemAttrSync* other);

  // implements Message ----------------------------------------------

  ItemAttrSync* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemAttrSync& from);
  void MergeFrom(const ItemAttrSync& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ItemAttrSync_Attr Attr;

  // accessors -------------------------------------------------------

  // optional int64 itemid = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 1;
  inline ::google::protobuf::int64 itemid() const;
  inline void set_itemid(::google::protobuf::int64 value);

  // repeated .Message.ItemAttrSync.Attr attr = 2;
  inline int attr_size() const;
  inline void clear_attr();
  static const int kAttrFieldNumber = 2;
  inline const ::Message::ItemAttrSync_Attr& attr(int index) const;
  inline ::Message::ItemAttrSync_Attr* mutable_attr(int index);
  inline ::Message::ItemAttrSync_Attr* add_attr();
  inline const ::google::protobuf::RepeatedPtrField< ::Message::ItemAttrSync_Attr >&
      attr() const;
  inline ::google::protobuf::RepeatedPtrField< ::Message::ItemAttrSync_Attr >*
      mutable_attr();

  // @@protoc_insertion_point(class_scope:Message.ItemAttrSync)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 itemid_;
  ::google::protobuf::RepeatedPtrField< ::Message::ItemAttrSync_Attr > attr_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItem_2eproto();
  friend void protobuf_AssignDesc_MessageItem_2eproto();
  friend void protobuf_ShutdownFile_MessageItem_2eproto();

  void InitAsDefaultInstance();
  static ItemAttrSync* default_instance_;
};
// ===================================================================


// ===================================================================

// ItemGainSync

// optional int64 itemid = 1;
inline bool ItemGainSync::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemGainSync::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemGainSync::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemGainSync::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
  clear_has_itemid();
}
inline ::google::protobuf::int64 ItemGainSync::itemid() const {
  return itemid_;
}
inline void ItemGainSync::set_itemid(::google::protobuf::int64 value) {
  set_has_itemid();
  itemid_ = value;
}

// optional int32 templateid = 2;
inline bool ItemGainSync::has_templateid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ItemGainSync::set_has_templateid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ItemGainSync::clear_has_templateid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ItemGainSync::clear_templateid() {
  templateid_ = 0;
  clear_has_templateid();
}
inline ::google::protobuf::int32 ItemGainSync::templateid() const {
  return templateid_;
}
inline void ItemGainSync::set_templateid(::google::protobuf::int32 value) {
  set_has_templateid();
  templateid_ = value;
}

// optional int32 stack = 3;
inline bool ItemGainSync::has_stack() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ItemGainSync::set_has_stack() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ItemGainSync::clear_has_stack() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ItemGainSync::clear_stack() {
  stack_ = 0;
  clear_has_stack();
}
inline ::google::protobuf::int32 ItemGainSync::stack() const {
  return stack_;
}
inline void ItemGainSync::set_stack(::google::protobuf::int32 value) {
  set_has_stack();
  stack_ = value;
}

// optional int32 position = 4;
inline bool ItemGainSync::has_position() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ItemGainSync::set_has_position() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ItemGainSync::clear_has_position() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ItemGainSync::clear_position() {
  position_ = 0;
  clear_has_position();
}
inline ::google::protobuf::int32 ItemGainSync::position() const {
  return position_;
}
inline void ItemGainSync::set_position(::google::protobuf::int32 value) {
  set_has_position();
  position_ = value;
}

// optional int64 parent = 5;
inline bool ItemGainSync::has_parent() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ItemGainSync::set_has_parent() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ItemGainSync::clear_has_parent() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ItemGainSync::clear_parent() {
  parent_ = GOOGLE_LONGLONG(0);
  clear_has_parent();
}
inline ::google::protobuf::int64 ItemGainSync::parent() const {
  return parent_;
}
inline void ItemGainSync::set_parent(::google::protobuf::int64 value) {
  set_has_parent();
  parent_ = value;
}

// optional int64 equipid = 6;
inline bool ItemGainSync::has_equipid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ItemGainSync::set_has_equipid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ItemGainSync::clear_has_equipid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ItemGainSync::clear_equipid() {
  equipid_ = GOOGLE_LONGLONG(0);
  clear_has_equipid();
}
inline ::google::protobuf::int64 ItemGainSync::equipid() const {
  return equipid_;
}
inline void ItemGainSync::set_equipid(::google::protobuf::int64 value) {
  set_has_equipid();
  equipid_ = value;
}

// optional int32 intensify = 7;
inline bool ItemGainSync::has_intensify() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ItemGainSync::set_has_intensify() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ItemGainSync::clear_has_intensify() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ItemGainSync::clear_intensify() {
  intensify_ = 0;
  clear_has_intensify();
}
inline ::google::protobuf::int32 ItemGainSync::intensify() const {
  return intensify_;
}
inline void ItemGainSync::set_intensify(::google::protobuf::int32 value) {
  set_has_intensify();
  intensify_ = value;
}

// -------------------------------------------------------------------

// ItemDeleteSync

// optional int64 itemid = 1;
inline bool ItemDeleteSync::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemDeleteSync::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemDeleteSync::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemDeleteSync::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
  clear_has_itemid();
}
inline ::google::protobuf::int64 ItemDeleteSync::itemid() const {
  return itemid_;
}
inline void ItemDeleteSync::set_itemid(::google::protobuf::int64 value) {
  set_has_itemid();
  itemid_ = value;
}

// -------------------------------------------------------------------

// ItemUseRequest

// optional int64 itemid = 1;
inline bool ItemUseRequest::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemUseRequest::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemUseRequest::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemUseRequest::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
  clear_has_itemid();
}
inline ::google::protobuf::int64 ItemUseRequest::itemid() const {
  return itemid_;
}
inline void ItemUseRequest::set_itemid(::google::protobuf::int64 value) {
  set_has_itemid();
  itemid_ = value;
}

// -------------------------------------------------------------------

// ItemDeleteRequest

// optional int64 itemid = 1;
inline bool ItemDeleteRequest::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemDeleteRequest::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemDeleteRequest::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemDeleteRequest::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
  clear_has_itemid();
}
inline ::google::protobuf::int64 ItemDeleteRequest::itemid() const {
  return itemid_;
}
inline void ItemDeleteRequest::set_itemid(::google::protobuf::int64 value) {
  set_has_itemid();
  itemid_ = value;
}

// -------------------------------------------------------------------

// ItemSellRequest

// optional int64 itemid = 1;
inline bool ItemSellRequest::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemSellRequest::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemSellRequest::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemSellRequest::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
  clear_has_itemid();
}
inline ::google::protobuf::int64 ItemSellRequest::itemid() const {
  return itemid_;
}
inline void ItemSellRequest::set_itemid(::google::protobuf::int64 value) {
  set_has_itemid();
  itemid_ = value;
}

// -------------------------------------------------------------------

// ItemEquipRequest

// optional int64 itemid = 1;
inline bool ItemEquipRequest::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemEquipRequest::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemEquipRequest::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemEquipRequest::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
  clear_has_itemid();
}
inline ::google::protobuf::int64 ItemEquipRequest::itemid() const {
  return itemid_;
}
inline void ItemEquipRequest::set_itemid(::google::protobuf::int64 value) {
  set_has_itemid();
  itemid_ = value;
}

// optional int64 roleid = 2;
inline bool ItemEquipRequest::has_roleid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ItemEquipRequest::set_has_roleid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ItemEquipRequest::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ItemEquipRequest::clear_roleid() {
  roleid_ = GOOGLE_LONGLONG(0);
  clear_has_roleid();
}
inline ::google::protobuf::int64 ItemEquipRequest::roleid() const {
  return roleid_;
}
inline void ItemEquipRequest::set_roleid(::google::protobuf::int64 value) {
  set_has_roleid();
  roleid_ = value;
}

// -------------------------------------------------------------------

// ItemUnequipRequest

// optional int64 itemid = 1;
inline bool ItemUnequipRequest::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemUnequipRequest::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemUnequipRequest::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemUnequipRequest::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
  clear_has_itemid();
}
inline ::google::protobuf::int64 ItemUnequipRequest::itemid() const {
  return itemid_;
}
inline void ItemUnequipRequest::set_itemid(::google::protobuf::int64 value) {
  set_has_itemid();
  itemid_ = value;
}

// optional int64 roleid = 2;
inline bool ItemUnequipRequest::has_roleid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ItemUnequipRequest::set_has_roleid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ItemUnequipRequest::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ItemUnequipRequest::clear_roleid() {
  roleid_ = GOOGLE_LONGLONG(0);
  clear_has_roleid();
}
inline ::google::protobuf::int64 ItemUnequipRequest::roleid() const {
  return roleid_;
}
inline void ItemUnequipRequest::set_roleid(::google::protobuf::int64 value) {
  set_has_roleid();
  roleid_ = value;
}

// optional int32 position = 3;
inline bool ItemUnequipRequest::has_position() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ItemUnequipRequest::set_has_position() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ItemUnequipRequest::clear_has_position() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ItemUnequipRequest::clear_position() {
  position_ = 0;
  clear_has_position();
}
inline ::google::protobuf::int32 ItemUnequipRequest::position() const {
  return position_;
}
inline void ItemUnequipRequest::set_position(::google::protobuf::int32 value) {
  set_has_position();
  position_ = value;
}

// -------------------------------------------------------------------

// ItemAttrSync_Attr

// optional int32 type = 1;
inline bool ItemAttrSync_Attr::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemAttrSync_Attr::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemAttrSync_Attr::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemAttrSync_Attr::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 ItemAttrSync_Attr::type() const {
  return type_;
}
inline void ItemAttrSync_Attr::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// optional string group = 2;
inline bool ItemAttrSync_Attr::has_group() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ItemAttrSync_Attr::set_has_group() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ItemAttrSync_Attr::clear_has_group() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ItemAttrSync_Attr::clear_group() {
  if (group_ != &::google::protobuf::internal::kEmptyString) {
    group_->clear();
  }
  clear_has_group();
}
inline const ::std::string& ItemAttrSync_Attr::group() const {
  return *group_;
}
inline void ItemAttrSync_Attr::set_group(const ::std::string& value) {
  set_has_group();
  if (group_ == &::google::protobuf::internal::kEmptyString) {
    group_ = new ::std::string;
  }
  group_->assign(value);
}
inline void ItemAttrSync_Attr::set_group(const char* value) {
  set_has_group();
  if (group_ == &::google::protobuf::internal::kEmptyString) {
    group_ = new ::std::string;
  }
  group_->assign(value);
}
inline void ItemAttrSync_Attr::set_group(const char* value, size_t size) {
  set_has_group();
  if (group_ == &::google::protobuf::internal::kEmptyString) {
    group_ = new ::std::string;
  }
  group_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ItemAttrSync_Attr::mutable_group() {
  set_has_group();
  if (group_ == &::google::protobuf::internal::kEmptyString) {
    group_ = new ::std::string;
  }
  return group_;
}
inline ::std::string* ItemAttrSync_Attr::release_group() {
  clear_has_group();
  if (group_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = group_;
    group_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ItemAttrSync_Attr::set_allocated_group(::std::string* group) {
  if (group_ != &::google::protobuf::internal::kEmptyString) {
    delete group_;
  }
  if (group) {
    set_has_group();
    group_ = group;
  } else {
    clear_has_group();
    group_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string key = 3;
inline bool ItemAttrSync_Attr::has_key() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ItemAttrSync_Attr::set_has_key() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ItemAttrSync_Attr::clear_has_key() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ItemAttrSync_Attr::clear_key() {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& ItemAttrSync_Attr::key() const {
  return *key_;
}
inline void ItemAttrSync_Attr::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void ItemAttrSync_Attr::set_key(const char* value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void ItemAttrSync_Attr::set_key(const char* value, size_t size) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ItemAttrSync_Attr::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  return key_;
}
inline ::std::string* ItemAttrSync_Attr::release_key() {
  clear_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ItemAttrSync_Attr::set_allocated_key(::std::string* key) {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    delete key_;
  }
  if (key) {
    set_has_key();
    key_ = key;
  } else {
    clear_has_key();
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 val32 = 4;
inline bool ItemAttrSync_Attr::has_val32() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ItemAttrSync_Attr::set_has_val32() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ItemAttrSync_Attr::clear_has_val32() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ItemAttrSync_Attr::clear_val32() {
  val32_ = 0;
  clear_has_val32();
}
inline ::google::protobuf::int32 ItemAttrSync_Attr::val32() const {
  return val32_;
}
inline void ItemAttrSync_Attr::set_val32(::google::protobuf::int32 value) {
  set_has_val32();
  val32_ = value;
}

// optional int64 val64 = 5;
inline bool ItemAttrSync_Attr::has_val64() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ItemAttrSync_Attr::set_has_val64() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ItemAttrSync_Attr::clear_has_val64() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ItemAttrSync_Attr::clear_val64() {
  val64_ = GOOGLE_LONGLONG(0);
  clear_has_val64();
}
inline ::google::protobuf::int64 ItemAttrSync_Attr::val64() const {
  return val64_;
}
inline void ItemAttrSync_Attr::set_val64(::google::protobuf::int64 value) {
  set_has_val64();
  val64_ = value;
}

// optional string valstr = 6;
inline bool ItemAttrSync_Attr::has_valstr() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ItemAttrSync_Attr::set_has_valstr() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ItemAttrSync_Attr::clear_has_valstr() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ItemAttrSync_Attr::clear_valstr() {
  if (valstr_ != &::google::protobuf::internal::kEmptyString) {
    valstr_->clear();
  }
  clear_has_valstr();
}
inline const ::std::string& ItemAttrSync_Attr::valstr() const {
  return *valstr_;
}
inline void ItemAttrSync_Attr::set_valstr(const ::std::string& value) {
  set_has_valstr();
  if (valstr_ == &::google::protobuf::internal::kEmptyString) {
    valstr_ = new ::std::string;
  }
  valstr_->assign(value);
}
inline void ItemAttrSync_Attr::set_valstr(const char* value) {
  set_has_valstr();
  if (valstr_ == &::google::protobuf::internal::kEmptyString) {
    valstr_ = new ::std::string;
  }
  valstr_->assign(value);
}
inline void ItemAttrSync_Attr::set_valstr(const char* value, size_t size) {
  set_has_valstr();
  if (valstr_ == &::google::protobuf::internal::kEmptyString) {
    valstr_ = new ::std::string;
  }
  valstr_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ItemAttrSync_Attr::mutable_valstr() {
  set_has_valstr();
  if (valstr_ == &::google::protobuf::internal::kEmptyString) {
    valstr_ = new ::std::string;
  }
  return valstr_;
}
inline ::std::string* ItemAttrSync_Attr::release_valstr() {
  clear_has_valstr();
  if (valstr_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = valstr_;
    valstr_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ItemAttrSync_Attr::set_allocated_valstr(::std::string* valstr) {
  if (valstr_ != &::google::protobuf::internal::kEmptyString) {
    delete valstr_;
  }
  if (valstr) {
    set_has_valstr();
    valstr_ = valstr;
  } else {
    clear_has_valstr();
    valstr_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// ItemAttrSync

// optional int64 itemid = 1;
inline bool ItemAttrSync::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemAttrSync::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemAttrSync::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemAttrSync::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
  clear_has_itemid();
}
inline ::google::protobuf::int64 ItemAttrSync::itemid() const {
  return itemid_;
}
inline void ItemAttrSync::set_itemid(::google::protobuf::int64 value) {
  set_has_itemid();
  itemid_ = value;
}

// repeated .Message.ItemAttrSync.Attr attr = 2;
inline int ItemAttrSync::attr_size() const {
  return attr_.size();
}
inline void ItemAttrSync::clear_attr() {
  attr_.Clear();
}
inline const ::Message::ItemAttrSync_Attr& ItemAttrSync::attr(int index) const {
  return attr_.Get(index);
}
inline ::Message::ItemAttrSync_Attr* ItemAttrSync::mutable_attr(int index) {
  return attr_.Mutable(index);
}
inline ::Message::ItemAttrSync_Attr* ItemAttrSync::add_attr() {
  return attr_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Message::ItemAttrSync_Attr >&
ItemAttrSync::attr() const {
  return attr_;
}
inline ::google::protobuf::RepeatedPtrField< ::Message::ItemAttrSync_Attr >*
ItemAttrSync::mutable_attr() {
  return &attr_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageItem_2eproto__INCLUDED
