// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageInlayAll.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageInlayAll.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Message {

namespace {

const ::google::protobuf::Descriptor* MessageInlayEntity_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageInlayEntity_reflection_ = NULL;
const ::google::protobuf::Descriptor* MessageInlayAllRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageInlayAllRequest_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageInlayAll_2eproto() {
  protobuf_AddDesc_MessageInlayAll_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageInlayAll.proto");
  GOOGLE_CHECK(file != NULL);
  MessageInlayEntity_descriptor_ = file->message_type(0);
  static const int MessageInlayEntity_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageInlayEntity, itemid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageInlayEntity, soulid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageInlayEntity, holeindex_),
  };
  MessageInlayEntity_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageInlayEntity_descriptor_,
      MessageInlayEntity::default_instance_,
      MessageInlayEntity_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageInlayEntity, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageInlayEntity, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageInlayEntity));
  MessageInlayAllRequest_descriptor_ = file->message_type(1);
  static const int MessageInlayAllRequest_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageInlayAllRequest, roleid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageInlayAllRequest, values_),
  };
  MessageInlayAllRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageInlayAllRequest_descriptor_,
      MessageInlayAllRequest::default_instance_,
      MessageInlayAllRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageInlayAllRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageInlayAllRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageInlayAllRequest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageInlayAll_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageInlayEntity_descriptor_, &MessageInlayEntity::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageInlayAllRequest_descriptor_, &MessageInlayAllRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageInlayAll_2eproto() {
  delete MessageInlayEntity::default_instance_;
  delete MessageInlayEntity_reflection_;
  delete MessageInlayAllRequest::default_instance_;
  delete MessageInlayAllRequest_reflection_;
}

void protobuf_AddDesc_MessageInlayAll_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025MessageInlayAll.proto\022\007Message\"G\n\022Mess"
    "ageInlayEntity\022\016\n\006itemId\030\001 \001(\003\022\016\n\006soulId"
    "\030\002 \001(\003\022\021\n\tholeIndex\030\003 \001(\005\"U\n\026MessageInla"
    "yAllRequest\022\016\n\006roleId\030\001 \001(\003\022+\n\006values\030\002 "
    "\003(\0132\033.Message.MessageInlayEntity", 192);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageInlayAll.proto", &protobuf_RegisterTypes);
  MessageInlayEntity::default_instance_ = new MessageInlayEntity();
  MessageInlayAllRequest::default_instance_ = new MessageInlayAllRequest();
  MessageInlayEntity::default_instance_->InitAsDefaultInstance();
  MessageInlayAllRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageInlayAll_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageInlayAll_2eproto {
  StaticDescriptorInitializer_MessageInlayAll_2eproto() {
    protobuf_AddDesc_MessageInlayAll_2eproto();
  }
} static_descriptor_initializer_MessageInlayAll_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessageInlayEntity::kItemIdFieldNumber;
const int MessageInlayEntity::kSoulIdFieldNumber;
const int MessageInlayEntity::kHoleIndexFieldNumber;
#endif  // !_MSC_VER

MessageInlayEntity::MessageInlayEntity()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MessageInlayEntity::InitAsDefaultInstance() {
}

MessageInlayEntity::MessageInlayEntity(const MessageInlayEntity& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MessageInlayEntity::SharedCtor() {
  _cached_size_ = 0;
  itemid_ = GOOGLE_LONGLONG(0);
  soulid_ = GOOGLE_LONGLONG(0);
  holeindex_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageInlayEntity::~MessageInlayEntity() {
  SharedDtor();
}

void MessageInlayEntity::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MessageInlayEntity::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageInlayEntity::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageInlayEntity_descriptor_;
}

const MessageInlayEntity& MessageInlayEntity::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageInlayAll_2eproto();
  return *default_instance_;
}

MessageInlayEntity* MessageInlayEntity::default_instance_ = NULL;

MessageInlayEntity* MessageInlayEntity::New() const {
  return new MessageInlayEntity;
}

void MessageInlayEntity::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    itemid_ = GOOGLE_LONGLONG(0);
    soulid_ = GOOGLE_LONGLONG(0);
    holeindex_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageInlayEntity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 itemId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &itemid_)));
          set_has_itemid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_soulId;
        break;
      }

      // optional int64 soulId = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_soulId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &soulid_)));
          set_has_soulid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_holeIndex;
        break;
      }

      // optional int32 holeIndex = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_holeIndex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &holeindex_)));
          set_has_holeindex();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MessageInlayEntity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int64 itemId = 1;
  if (has_itemid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->itemid(), output);
  }

  // optional int64 soulId = 2;
  if (has_soulid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->soulid(), output);
  }

  // optional int32 holeIndex = 3;
  if (has_holeindex()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->holeindex(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MessageInlayEntity::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int64 itemId = 1;
  if (has_itemid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->itemid(), target);
  }

  // optional int64 soulId = 2;
  if (has_soulid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->soulid(), target);
  }

  // optional int32 holeIndex = 3;
  if (has_holeindex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->holeindex(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MessageInlayEntity::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int64 itemId = 1;
    if (has_itemid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->itemid());
    }

    // optional int64 soulId = 2;
    if (has_soulid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->soulid());
    }

    // optional int32 holeIndex = 3;
    if (has_holeindex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->holeindex());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageInlayEntity::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageInlayEntity* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageInlayEntity*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageInlayEntity::MergeFrom(const MessageInlayEntity& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_itemid()) {
      set_itemid(from.itemid());
    }
    if (from.has_soulid()) {
      set_soulid(from.soulid());
    }
    if (from.has_holeindex()) {
      set_holeindex(from.holeindex());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageInlayEntity::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageInlayEntity::CopyFrom(const MessageInlayEntity& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageInlayEntity::IsInitialized() const {

  return true;
}

void MessageInlayEntity::Swap(MessageInlayEntity* other) {
  if (other != this) {
    std::swap(itemid_, other->itemid_);
    std::swap(soulid_, other->soulid_);
    std::swap(holeindex_, other->holeindex_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageInlayEntity::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageInlayEntity_descriptor_;
  metadata.reflection = MessageInlayEntity_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MessageInlayAllRequest::kRoleIdFieldNumber;
const int MessageInlayAllRequest::kValuesFieldNumber;
#endif  // !_MSC_VER

MessageInlayAllRequest::MessageInlayAllRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MessageInlayAllRequest::InitAsDefaultInstance() {
}

MessageInlayAllRequest::MessageInlayAllRequest(const MessageInlayAllRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MessageInlayAllRequest::SharedCtor() {
  _cached_size_ = 0;
  roleid_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageInlayAllRequest::~MessageInlayAllRequest() {
  SharedDtor();
}

void MessageInlayAllRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MessageInlayAllRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageInlayAllRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageInlayAllRequest_descriptor_;
}

const MessageInlayAllRequest& MessageInlayAllRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageInlayAll_2eproto();
  return *default_instance_;
}

MessageInlayAllRequest* MessageInlayAllRequest::default_instance_ = NULL;

MessageInlayAllRequest* MessageInlayAllRequest::New() const {
  return new MessageInlayAllRequest;
}

void MessageInlayAllRequest::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    roleid_ = GOOGLE_LONGLONG(0);
  }
  values_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageInlayAllRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 roleId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &roleid_)));
          set_has_roleid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_values;
        break;
      }

      // repeated .Message.MessageInlayEntity values = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_values:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_values()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_values;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MessageInlayAllRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int64 roleId = 1;
  if (has_roleid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->roleid(), output);
  }

  // repeated .Message.MessageInlayEntity values = 2;
  for (int i = 0; i < this->values_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->values(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MessageInlayAllRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int64 roleId = 1;
  if (has_roleid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->roleid(), target);
  }

  // repeated .Message.MessageInlayEntity values = 2;
  for (int i = 0; i < this->values_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->values(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MessageInlayAllRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int64 roleId = 1;
    if (has_roleid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->roleid());
    }

  }
  // repeated .Message.MessageInlayEntity values = 2;
  total_size += 1 * this->values_size();
  for (int i = 0; i < this->values_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->values(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageInlayAllRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageInlayAllRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageInlayAllRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageInlayAllRequest::MergeFrom(const MessageInlayAllRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  values_.MergeFrom(from.values_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_roleid()) {
      set_roleid(from.roleid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageInlayAllRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageInlayAllRequest::CopyFrom(const MessageInlayAllRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageInlayAllRequest::IsInitialized() const {

  return true;
}

void MessageInlayAllRequest::Swap(MessageInlayAllRequest* other) {
  if (other != this) {
    std::swap(roleid_, other->roleid_);
    values_.Swap(&other->values_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageInlayAllRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageInlayAllRequest_descriptor_;
  metadata.reflection = MessageInlayAllRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

// @@protoc_insertion_point(global_scope)
