// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageTrainUnSaveRequest.proto

#ifndef PROTOBUF_MessageTrainUnSaveRequest_2eproto__INCLUDED
#define PROTOBUF_MessageTrainUnSaveRequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageTrainUnSaveRequest_2eproto();
void protobuf_AssignDesc_MessageTrainUnSaveRequest_2eproto();
void protobuf_ShutdownFile_MessageTrainUnSaveRequest_2eproto();

class TrainUnSaveRequest;

// ===================================================================

class TrainUnSaveRequest : public ::google::protobuf::Message {
 public:
  TrainUnSaveRequest();
  virtual ~TrainUnSaveRequest();

  TrainUnSaveRequest(const TrainUnSaveRequest& from);

  inline TrainUnSaveRequest& operator=(const TrainUnSaveRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrainUnSaveRequest& default_instance();

  void Swap(TrainUnSaveRequest* other);

  // implements Message ----------------------------------------------

  TrainUnSaveRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrainUnSaveRequest& from);
  void MergeFrom(const TrainUnSaveRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 role = 1;
  inline bool has_role() const;
  inline void clear_role();
  static const int kRoleFieldNumber = 1;
  inline ::google::protobuf::int64 role() const;
  inline void set_role(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Message.TrainUnSaveRequest)
 private:
  inline void set_has_role();
  inline void clear_has_role();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 role_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MessageTrainUnSaveRequest_2eproto();
  friend void protobuf_AssignDesc_MessageTrainUnSaveRequest_2eproto();
  friend void protobuf_ShutdownFile_MessageTrainUnSaveRequest_2eproto();

  void InitAsDefaultInstance();
  static TrainUnSaveRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// TrainUnSaveRequest

// optional int64 role = 1;
inline bool TrainUnSaveRequest::has_role() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TrainUnSaveRequest::set_has_role() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TrainUnSaveRequest::clear_has_role() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TrainUnSaveRequest::clear_role() {
  role_ = GOOGLE_LONGLONG(0);
  clear_has_role();
}
inline ::google::protobuf::int64 TrainUnSaveRequest::role() const {
  return role_;
}
inline void TrainUnSaveRequest::set_role(::google::protobuf::int64 value) {
  set_has_role();
  role_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageTrainUnSaveRequest_2eproto__INCLUDED
