// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageItemGainResponse.proto

#ifndef PROTOBUF_MessageItemGainResponse_2eproto__INCLUDED
#define PROTOBUF_MessageItemGainResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageItemGainResponse_2eproto();
void protobuf_AssignDesc_MessageItemGainResponse_2eproto();
void protobuf_ShutdownFile_MessageItemGainResponse_2eproto();

class ItemGainResponse;
class ItemGainResponse_Soul;

// ===================================================================

class ItemGainResponse_Soul : public ::google::protobuf::Message {
 public:
  ItemGainResponse_Soul();
  virtual ~ItemGainResponse_Soul();

  ItemGainResponse_Soul(const ItemGainResponse_Soul& from);

  inline ItemGainResponse_Soul& operator=(const ItemGainResponse_Soul& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemGainResponse_Soul& default_instance();

  void Swap(ItemGainResponse_Soul* other);

  // implements Message ----------------------------------------------

  ItemGainResponse_Soul* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemGainResponse_Soul& from);
  void MergeFrom(const ItemGainResponse_Soul& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 template_id = 1;
  inline bool has_template_id() const;
  inline void clear_template_id();
  static const int kTemplateIdFieldNumber = 1;
  inline ::google::protobuf::int32 template_id() const;
  inline void set_template_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.ItemGainResponse.Soul)
 private:
  inline void set_has_template_id();
  inline void clear_has_template_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 template_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItemGainResponse_2eproto();
  friend void protobuf_AssignDesc_MessageItemGainResponse_2eproto();
  friend void protobuf_ShutdownFile_MessageItemGainResponse_2eproto();

  void InitAsDefaultInstance();
  static ItemGainResponse_Soul* default_instance_;
};
// -------------------------------------------------------------------

class ItemGainResponse : public ::google::protobuf::Message {
 public:
  ItemGainResponse();
  virtual ~ItemGainResponse();

  ItemGainResponse(const ItemGainResponse& from);

  inline ItemGainResponse& operator=(const ItemGainResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemGainResponse& default_instance();

  void Swap(ItemGainResponse* other);

  // implements Message ----------------------------------------------

  ItemGainResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemGainResponse& from);
  void MergeFrom(const ItemGainResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ItemGainResponse_Soul Soul;

  // accessors -------------------------------------------------------

  // optional int64 itemid = 1;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemidFieldNumber = 1;
  inline ::google::protobuf::int64 itemid() const;
  inline void set_itemid(::google::protobuf::int64 value);

  // optional int32 templateid = 2;
  inline bool has_templateid() const;
  inline void clear_templateid();
  static const int kTemplateidFieldNumber = 2;
  inline ::google::protobuf::int32 templateid() const;
  inline void set_templateid(::google::protobuf::int32 value);

  // optional int32 stack = 3;
  inline bool has_stack() const;
  inline void clear_stack();
  static const int kStackFieldNumber = 3;
  inline ::google::protobuf::int32 stack() const;
  inline void set_stack(::google::protobuf::int32 value);

  // optional int32 position = 4;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 4;
  inline ::google::protobuf::int32 position() const;
  inline void set_position(::google::protobuf::int32 value);

  // optional int64 parent_id = 5;
  inline bool has_parent_id() const;
  inline void clear_parent_id();
  static const int kParentIdFieldNumber = 5;
  inline ::google::protobuf::int64 parent_id() const;
  inline void set_parent_id(::google::protobuf::int64 value);

  // optional int64 equip_hero_id = 6;
  inline bool has_equip_hero_id() const;
  inline void clear_equip_hero_id();
  static const int kEquipHeroIdFieldNumber = 6;
  inline ::google::protobuf::int64 equip_hero_id() const;
  inline void set_equip_hero_id(::google::protobuf::int64 value);

  // repeated .Message.ItemGainResponse.Soul seconds = 7;
  inline int seconds_size() const;
  inline void clear_seconds();
  static const int kSecondsFieldNumber = 7;
  inline const ::Message::ItemGainResponse_Soul& seconds(int index) const;
  inline ::Message::ItemGainResponse_Soul* mutable_seconds(int index);
  inline ::Message::ItemGainResponse_Soul* add_seconds();
  inline const ::google::protobuf::RepeatedPtrField< ::Message::ItemGainResponse_Soul >&
      seconds() const;
  inline ::google::protobuf::RepeatedPtrField< ::Message::ItemGainResponse_Soul >*
      mutable_seconds();

  // optional int32 current_intensify_level = 8;
  inline bool has_current_intensify_level() const;
  inline void clear_current_intensify_level();
  static const int kCurrentIntensifyLevelFieldNumber = 8;
  inline ::google::protobuf::int32 current_intensify_level() const;
  inline void set_current_intensify_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Message.ItemGainResponse)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_templateid();
  inline void clear_has_templateid();
  inline void set_has_stack();
  inline void clear_has_stack();
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_parent_id();
  inline void clear_has_parent_id();
  inline void set_has_equip_hero_id();
  inline void clear_has_equip_hero_id();
  inline void set_has_current_intensify_level();
  inline void clear_has_current_intensify_level();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 itemid_;
  ::google::protobuf::int32 templateid_;
  ::google::protobuf::int32 stack_;
  ::google::protobuf::int64 parent_id_;
  ::google::protobuf::int64 equip_hero_id_;
  ::google::protobuf::int32 position_;
  ::google::protobuf::int32 current_intensify_level_;
  ::google::protobuf::RepeatedPtrField< ::Message::ItemGainResponse_Soul > seconds_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_MessageItemGainResponse_2eproto();
  friend void protobuf_AssignDesc_MessageItemGainResponse_2eproto();
  friend void protobuf_ShutdownFile_MessageItemGainResponse_2eproto();

  void InitAsDefaultInstance();
  static ItemGainResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// ItemGainResponse_Soul

// optional int32 template_id = 1;
inline bool ItemGainResponse_Soul::has_template_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemGainResponse_Soul::set_has_template_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemGainResponse_Soul::clear_has_template_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemGainResponse_Soul::clear_template_id() {
  template_id_ = 0;
  clear_has_template_id();
}
inline ::google::protobuf::int32 ItemGainResponse_Soul::template_id() const {
  return template_id_;
}
inline void ItemGainResponse_Soul::set_template_id(::google::protobuf::int32 value) {
  set_has_template_id();
  template_id_ = value;
}

// -------------------------------------------------------------------

// ItemGainResponse

// optional int64 itemid = 1;
inline bool ItemGainResponse::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ItemGainResponse::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ItemGainResponse::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ItemGainResponse::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
  clear_has_itemid();
}
inline ::google::protobuf::int64 ItemGainResponse::itemid() const {
  return itemid_;
}
inline void ItemGainResponse::set_itemid(::google::protobuf::int64 value) {
  set_has_itemid();
  itemid_ = value;
}

// optional int32 templateid = 2;
inline bool ItemGainResponse::has_templateid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ItemGainResponse::set_has_templateid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ItemGainResponse::clear_has_templateid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ItemGainResponse::clear_templateid() {
  templateid_ = 0;
  clear_has_templateid();
}
inline ::google::protobuf::int32 ItemGainResponse::templateid() const {
  return templateid_;
}
inline void ItemGainResponse::set_templateid(::google::protobuf::int32 value) {
  set_has_templateid();
  templateid_ = value;
}

// optional int32 stack = 3;
inline bool ItemGainResponse::has_stack() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ItemGainResponse::set_has_stack() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ItemGainResponse::clear_has_stack() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ItemGainResponse::clear_stack() {
  stack_ = 0;
  clear_has_stack();
}
inline ::google::protobuf::int32 ItemGainResponse::stack() const {
  return stack_;
}
inline void ItemGainResponse::set_stack(::google::protobuf::int32 value) {
  set_has_stack();
  stack_ = value;
}

// optional int32 position = 4;
inline bool ItemGainResponse::has_position() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ItemGainResponse::set_has_position() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ItemGainResponse::clear_has_position() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ItemGainResponse::clear_position() {
  position_ = 0;
  clear_has_position();
}
inline ::google::protobuf::int32 ItemGainResponse::position() const {
  return position_;
}
inline void ItemGainResponse::set_position(::google::protobuf::int32 value) {
  set_has_position();
  position_ = value;
}

// optional int64 parent_id = 5;
inline bool ItemGainResponse::has_parent_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ItemGainResponse::set_has_parent_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ItemGainResponse::clear_has_parent_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ItemGainResponse::clear_parent_id() {
  parent_id_ = GOOGLE_LONGLONG(0);
  clear_has_parent_id();
}
inline ::google::protobuf::int64 ItemGainResponse::parent_id() const {
  return parent_id_;
}
inline void ItemGainResponse::set_parent_id(::google::protobuf::int64 value) {
  set_has_parent_id();
  parent_id_ = value;
}

// optional int64 equip_hero_id = 6;
inline bool ItemGainResponse::has_equip_hero_id() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ItemGainResponse::set_has_equip_hero_id() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ItemGainResponse::clear_has_equip_hero_id() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ItemGainResponse::clear_equip_hero_id() {
  equip_hero_id_ = GOOGLE_LONGLONG(0);
  clear_has_equip_hero_id();
}
inline ::google::protobuf::int64 ItemGainResponse::equip_hero_id() const {
  return equip_hero_id_;
}
inline void ItemGainResponse::set_equip_hero_id(::google::protobuf::int64 value) {
  set_has_equip_hero_id();
  equip_hero_id_ = value;
}

// repeated .Message.ItemGainResponse.Soul seconds = 7;
inline int ItemGainResponse::seconds_size() const {
  return seconds_.size();
}
inline void ItemGainResponse::clear_seconds() {
  seconds_.Clear();
}
inline const ::Message::ItemGainResponse_Soul& ItemGainResponse::seconds(int index) const {
  return seconds_.Get(index);
}
inline ::Message::ItemGainResponse_Soul* ItemGainResponse::mutable_seconds(int index) {
  return seconds_.Mutable(index);
}
inline ::Message::ItemGainResponse_Soul* ItemGainResponse::add_seconds() {
  return seconds_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Message::ItemGainResponse_Soul >&
ItemGainResponse::seconds() const {
  return seconds_;
}
inline ::google::protobuf::RepeatedPtrField< ::Message::ItemGainResponse_Soul >*
ItemGainResponse::mutable_seconds() {
  return &seconds_;
}

// optional int32 current_intensify_level = 8;
inline bool ItemGainResponse::has_current_intensify_level() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ItemGainResponse::set_has_current_intensify_level() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ItemGainResponse::clear_has_current_intensify_level() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ItemGainResponse::clear_current_intensify_level() {
  current_intensify_level_ = 0;
  clear_has_current_intensify_level();
}
inline ::google::protobuf::int32 ItemGainResponse::current_intensify_level() const {
  return current_intensify_level_;
}
inline void ItemGainResponse::set_current_intensify_level(::google::protobuf::int32 value) {
  set_has_current_intensify_level();
  current_intensify_level_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageItemGainResponse_2eproto__INCLUDED
